generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: DmMailDecorator
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: dm_mail_decorator
    with_doctrine_route: false
    i18n_catalogue: dm
    config:
      actions: ~
      fields:
        is_active:
          label: Active
        template:
          is_big: true
        show_vars:
          is_big: true
      list:
        display:
          - '=name'
          - mail_templates_list
          - created_at
          - updated_at
          - is_active
        sort:
          - created_at
          - desc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: false
      filter:
        display:
          - name
          - created_at
          - updated_at
          - is_active
      form:
        display:
          NONE: [name, is_active]
          'Mail templates': [mail_templates_list]
          Content: [_show_vars,template]
        class: DmMailDecoratorAdminForm
        fields: {  }
      edit: ~
      new: ~
