<?php

/**
 * Config handler for Behaviors
 *
 * @author TheCelavi
 */
class dmBehaviorsConfigHandler extends sfYamlConfigHandler {
    
    public function execute($configFiles) {
        $config = array();
        $behaviors = array();
        foreach ($configFiles as $file) {
            $tmp = $this->parseYaml($file);
            if(!isset($tmp['dmBehaviors'])) continue;
            foreach($tmp['dmBehaviors'] as $key=>$value) {
                $sectionKey = dmString::slugify($value['section']);
                if (!isset($config[$sectionKey])) {
                    $config[$sectionKey] = array(
                        'section_name' => $value['section'],
                        'behaviors' => array()
                    );
                    
                } 
                $config[$sectionKey]['behaviors'][$key] = array(
                    'name' => (isset($value['name'])) ? $value['name'] : dmString::humanize($key),
                    'icon' => (isset($value['icon'])) ? $value['icon'] : '/dmCorePlugin/images/16/gear.png',
                    'form' => (isset($value['form'])) ? $value['form'] : 'dm'.dmString::camelize($key).'BehaviorForm',
                    'view' => (isset($value['view'])) ? $value['view'] : 'dm'.dmString::camelize($key).'BehaviorView',
                    'cache' => (isset($value['cache'])) ? (bool) $value['cache'] : true
                );
                $behaviors[$key] = $config[$sectionKey]['behaviors'][$key];
            }
        }
        
        $retval = sprintf("<?php\n" .
                "// auto-generated by %s\n" .
                "// date: %s\nsfConfig::set('dm_behaviors_menu_items', \n%s\n);\n sfConfig::set('dm_behaviors', \n%s\n); \n ?>", __CLASS__, date('Y/m/d H:i:s'), var_export($config, true), var_export($behaviors, true));
        
        return $retval;
    }
    
}
