<?php

/**
 * PluginDmBehaviorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDmBehaviorTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDmBehaviorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDmBehavior');
    }
}