<?php

/**
 * PluginDmMailDecoratorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDmMailDecoratorTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDmMailDecoratorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDmMailDecorator');
    }
}