<?php

/**
 * PluginDmBehavior
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginDmBehavior extends BaseDmBehavior
{
    
    public function setValues($v) {
        $this->set('dm_behavior_value', json_encode($v));
    }
    
    public function getValues() {
        return (array) json_decode($this->get('dm_behavior_value'), true);
    }
    
}