<?php

/**
 * PluginDmMailDecorator
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginDmMailDecorator extends BaseDmMailDecorator
{
    public function postDelete($event)
    {
        parent::postDelete($event);
        dmContext::getInstance()->getServiceContainer()->getService('mail_renderer')->clearCache();
    }

    public function postUpdate($event)
    {
        parent::postUpdate($event);
        dmContext::getInstance()->getServiceContainer()->getService('mail_renderer')->clearCache();
    }

    public function postSave($event)
    {
        parent::postSave($event);
        dmContext::getInstance()->getServiceContainer()->getService('mail_renderer')->clearCache();
    }
}